datagrids:
    oauth-client-grid:
        source:
            type: orm
            query:
                select:
                    - client
                    - client.id
                    - client.name
                    - client.identifier
                    - client.grants
                    - client.active
                from:
                    - { table: Oro\Bundle\OAuth2ServerBundle\Entity\Client, alias: client }
        columns:
            name:
                label: oro.oauth2server.client.name.label
            identifier:
                label: oro.oauth2server.client.identifier.label
            active:
                label: oro.oauth2server.client.active.label
                frontend_type: boolean
        sorters:
            columns:
                name:
                    data_name: client.name
                active:
                    data_name: client.active
        filters:
            columns:
                name:
                    type: string
                    data_name: client.name
                active:
                    type: boolean
                    data_name: client.active
        properties:
            id: ~
            activate_link:
                type: url
                route: oro_oauth2_server_client_activate
                params: [ id ]
            deactivate_link:
                type: url
                route: oro_oauth2_server_client_deactivate
                params: [ id ]
            delete_link:
                type: url
                route: oro_oauth2_server_client_delete
                params: [ id ]
        actions:
            activate:
                type: ajax
                label: oro.oauth2server.client.action.activate
                icon: check
                link: activate_link
                acl_resource: oro_oauth2_edit
                defaultMessages:
                    success: oro.oauth2server.client.activate_success
            deactivate:
                type: ajax
                label: oro.oauth2server.client.action.deactivate
                icon: close
                link: deactivate_link
                confirmation: true
                acl_resource: oro_oauth2_edit
                defaultMessages:
                    confirm_title: oro.oauth2server.client.deactivate_confirm_title
                    confirm_content: oro.oauth2server.client.deactivate_confirm_message
                    success: oro.oauth2server.client.deactivate_success
            delete:
                type: ajaxdelete
                label: oro.grid.action.delete
                link: delete_link
                icon: trash
                acl_resource: oro_oauth2_delete
                defaultMessages:
                    confirm_content: oro.oauth2server.client.delete_confirm_message
                    success: oro.oauth2server.client.delete_success
        action_configuration: ['@oro_oauth2_server.client_action_visibility_provider', getActionsVisibility]
        options:
            entity_pagination: false
            entityHint: oro.oauth2server.client.datagrid.entity_hint

    oauth-client-backend-grid:
        extends: oauth-client-grid
        source:
            query:
                select:
                    - client.ownerEntityId
                    - client.ownerEntityClass
                    - client.frontend
                    - client.lastUsedAt
                where:
                    and:
                        - client.frontend = :frontend
            bind_parameters:
                - frontend
        columns:
            grants:
                label: oro.oauth2server.client.grants.label
                inline_editing:
                    enable: false
                type: twig
                frontend_type: html
                template: '@OroOAuth2Server/Client/Datagrid/grants.html.twig'
            lastUsedAt:
                label: oro.oauth2server.client.last_used_at.label
                frontend_type: datetime
        sorters:
            columns:
                lastUsedAt:
                    data_name: client.lastUsedAt
        filters:
            columns:
                lastUsedAt:
                    type: datetime
                    data_name: client.lastUsedAt
        properties:
            view_link:
                type:   url
                route:  oro_oauth2_view
                params: [ id ]
            update_link:
                type: url
                route: oro_oauth2_update
                params: [ id ]
        actions:
            view:
                type:         navigate
                label:        oro.grid.action.view
                link:         view_link
                icon:         eye
                rowAction:    true
            update:
                type: navigate
                label: oro.grid.action.update
                icon: edit
                link: update_link
                acl_resource: oro_oauth2_edit

    oauth-client-frontend-grid:
        extends: oauth-client-backend-grid
        properties:
            view_link:
                type:   url
                route:  oro_oauth2_frontend_view
                params: [ id ]
            update_link:
                type: url
                route: oro_oauth2_frontend_update
                params: [ id ]

    oauth-client-with-owner-grid:
        extends: oauth-client-grid
        source:
            query:
                where:
                    and:
                        - client.ownerEntityId = :ownerEntityId
                        - client.ownerEntityClass = :ownerEntityClass
            bind_parameters:
                - ownerEntityId
                - ownerEntityClass
        properties:
            id: ~
            update_link:
                type: url
                route: oro_oauth2_server_client_update
                params: [ id ]
        actions:
            update:
                type: dialog
                label: oro.grid.action.update
                icon: edit
                link: update_link
                acl_resource: oro_oauth2_edit
                widgetOptions:
                    reload-grid-name: oauth-client-with-owner-grid
                    options:
                        dialogOptions:
                            title: "@translator->trans(oro.oauth2server.client.dialog.edit_title)"
                            modal: true
                            width: 500
